[WIP] Proxy example
legionth/php-http-server-react pull request #20
Opened 2017-01-13 10:13 UTC by legionth

Currently based on #17

2017-01-13 11:36 UTC, clue commented
Nice! :+1: I'll review this more thoroughly once #17 is in.

2017-01-31 10:19 UTC, legionth commented
Ping @clue

2017-01-31 21:00 UTC, clue requested changes
Plenty of open issues here afaict, does it really make sense to address these here?

If we can provide a small example here, then I'm all for adding this here. Otherwise, *perhaps* move this elsewhere?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +        $dnsConnector = new DnsConnector($connector, $resolver);
Should probably only be injected once?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +        $host = $request->getHeader('Host')[0];
Tested across all versions? What if the host header is unset?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +        $hostArray = parse_url($host);
What if this fails?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +        $host = $request->getHeader('Host')[0];
What kind of request is being handled here? How is this verified at all?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +            });
backpressure?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +        $dnsConnector->create($host, $port)->then(function ($stream) use ($request, $resolve){
What if this fails?

2017-01-31 21:00 UTC, clue commented on examples/proxy.php
> +            });
Why does this need to buffer? What if the response is huge?

2017-02-07 12:35 UTC, legionth commented
This example would be to large to be a simple example. Will be handled in an seperated repo.

2017-02-07 12:35 UTC, closed without merging