Streaming requests
legionth/php-http-server-react pull request #27
Opened 2017-01-23 09:56 UTC by legionth

2017-01-23 09:56 UTC, legionth commented
Ping @clue

2017-01-23 10:41 UTC, clue requested changes
Can't await this feature :-) :+1:

2017-01-23 10:41 UTC, clue commented on src/HttpServer.php
> +                    $connection->write(RingCentral\Psr7\str(new Response(400)));
Motivation?

2017-01-23 10:41 UTC, clue commented on examples/streamReceivingServer.php
> +            $body->on('end', function () use (&$bodyContent, $resolve) {
Indentation is a bit off here. Also, I wonder why this is different from the example in the README?

2017-01-23 10:41 UTC, clue commented on src/HttpServer.php
> -        $protection = new CloseProtectionStream($connection);
Is this intentional? I wonder why this protection isn't needed anymore?

2017-01-23 10:41 UTC, clue commented on src/HttpServer.php
> +            $bodyStream->emit('end', array());
Not sure if this is tested, but could the connection keep emitting `data` events here?

2017-01-23 10:41 UTC, clue commented on tests/HttpServerTest.php
> +                $request->getBody()->on('end', function () use ($resolve) {
See also above. We likely need to explicitly ensure no `data` event will be emitted here. May also affect other tests afaict?

2017-01-23 11:40 UTC, legionth commented on src/HttpServer.php
> -        $protection = new CloseProtectionStream($connection);
No it wasn't :hospital:

2017-01-23 11:40 UTC, legionth commented on examples/streamReceivingServer.php
> +            $body->on('end', function () use (&$bodyContent, $resolve) {
In the newest commit these examples are equal.

2017-01-23 11:40 UTC, legionth commented on src/HttpServer.php
> +            $bodyStream->emit('end', array());
You are right. The  comment from below showed that data would be emitted.

2017-01-23 11:40 UTC, legionth commented on tests/HttpServerTest.php
> +                $request->getBody()->on('end', function () use ($resolve) {
I added an exception throw to some tests if any data will be emitted.

2017-01-23 11:56 UTC, legionth commented
Ping @clue

2017-01-23 12:17 UTC, clue requested changes

2017-01-23 12:17 UTC, clue commented on src/HttpBodyStream.php
> +        $this->input->removeListener('close', array($this, 'close'));
Is this needed? Closing the input should remove all listeners?

2017-01-23 12:17 UTC, clue commented on src/HttpServer.php
> +    public function sendResponse(ResponseInterface $response, ConnectionInterface $connection)
Is this related? Should this be a separate PR? Also looks like some tests were missing here?

2017-01-23 12:17 UTC, clue commented on README.md
> +Check out the `examples` folder how your server could look like.
The docs LGTM :+1: 

What if I happen have built on top of the existing version (non-streaming)? It looks like the upcoming version *only* supports streaming. Any recommendations/docs on how I should upgrade?

2017-01-23 12:17 UTC, clue commented on src/HttpServer.php
> +    public function sendResponse(ResponseInterface $response, ConnectionInterface $connection)
This should probably also be tested for invalid requests?

2017-01-23 12:37 UTC, legionth commented on src/HttpBodyStream.php
> +        $this->input->removeListener('close', array($this, 'close'));
Sure. When a connection is the input stream. The data will be still handled.

2017-01-23 13:08 UTC, clue commented on src/HttpBodyStream.php
> +        $this->input->removeListener('close', array($this, 'close'));
Not sure who's responsible here. The input stream will be closed 2 lines down. Shouldn't the input stop emitting events after it is closed?

If not, isn't the input misbehaving here? (and this should be fixed instead?)

2017-01-23 20:07 UTC, legionth commented on src/HttpBodyStream.php
> +        $this->input->removeListener('close', array($this, 'close'));
The input will stop I just thought it would be better to remove the listeners. But ok I'll remove them.

2017-01-23 20:10 UTC, legionth commented
Updated README and adjusted examples. I also thought about to remove the `Response` object as return value of the callback function and only allow promise. What do you think @clue ?

2017-01-23 21:14 UTC, clue approved these changes
Nice, LGTM! :+1: :tada: 

I guess this makes sense from a consistency perspective, but I kind of dislike how every handler now *has* to wait for the `end` event. I'm not sure this is something that can be addresses now, so I'll leave this up to you to decide :+1:

2017-01-23 21:17 UTC, clue commented
> remove the Response object as return value

Given the current flow, I guess this would make sense, but I kind of miss how easy the previous interface was...

I'm undecided currently, what do you think about this? What if I want to build a really simple API and don't want to care about request bodies at all?

2017-01-23 23:52 UTC, legionth commented
I think this is good Idea will add something before a new version. I think about something.

2017-01-25 11:07 UTC, legionth commented
Ping @clue. Added 2 commits.

2017-01-25 14:02 UTC, clue commented on src/HttpServer.php
> +            $bodyStream->close();
Does it make sense to close the stream *before* or *after* it is passed to the callback function?

A closed stream will not emit an `end` event, however, it's state could be checked via `isReadable()`.

I'm undecided, what do you think?

2017-01-25 14:02 UTC, clue approved these changes
Nice! The updated documentation makes this much much easier to grasp!

2017-01-26 18:18 UTC, merged